### ISSUE TITLE
Pull request 있고 conflict있길래 큰 고민 없이 Merge 해버렸네요...

### ISSUE THREAD

**Issue by flydog98** [seol11796/official_dataportal#5]
당연히 useage 파일들 추가되었을 줄 알고 Merge해버렸는데 주의 깊지 못했었네요. 아직 시간 더 필요하면 Revert 할 수도 있고, 아니라면 추가로 Merge할 수도 있을 것 같아요. 어느 쪽이 좋을지 저에게 말해주세요.

**Comment by seol11796** [comment]
usage 파일 추가된 부분 다시 올렸습니다 . 
comment 부분이 에러 나는 것으로 보여져서 comment 삭제하고 다시 푸시하겠습니다
